/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreditsRouteRouteImport } from './routes/credits/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreditsIndexRouteImport } from './routes/credits/index'
import { Route as CreditsCreditIdRouteImport } from './routes/credits/$creditId'

const CreditsRouteRoute = CreditsRouteRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsIndexRoute = CreditsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreditsRouteRoute,
} as any)
const CreditsCreditIdRoute = CreditsCreditIdRouteImport.update({
  id: '/$creditId',
  path: '/$creditId',
  getParentRoute: () => CreditsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRoute
  '/credits': typeof CreditsRouteRouteWithChildren
  '/credits/$creditId': typeof CreditsCreditIdRoute
  '/credits/': typeof CreditsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRoute
  '/credits/$creditId': typeof CreditsCreditIdRoute
  '/credits': typeof CreditsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRoute
  '/credits': typeof CreditsRouteRouteWithChildren
  '/credits/$creditId': typeof CreditsCreditIdRoute
  '/credits/': typeof CreditsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/credits' | '/credits/$creditId' | '/credits/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/credits/$creditId' | '/credits'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/credits'
    | '/credits/$creditId'
    | '/credits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRoute
  CreditsRouteRoute: typeof CreditsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits/': {
      id: '/credits/'
      path: '/'
      fullPath: '/credits/'
      preLoaderRoute: typeof CreditsIndexRouteImport
      parentRoute: typeof CreditsRouteRoute
    }
    '/credits/$creditId': {
      id: '/credits/$creditId'
      path: '/$creditId'
      fullPath: '/credits/$creditId'
      preLoaderRoute: typeof CreditsCreditIdRouteImport
      parentRoute: typeof CreditsRouteRoute
    }
  }
}

interface CreditsRouteRouteChildren {
  CreditsCreditIdRoute: typeof CreditsCreditIdRoute
  CreditsIndexRoute: typeof CreditsIndexRoute
}

const CreditsRouteRouteChildren: CreditsRouteRouteChildren = {
  CreditsCreditIdRoute: CreditsCreditIdRoute,
  CreditsIndexRoute: CreditsIndexRoute,
}

const CreditsRouteRouteWithChildren = CreditsRouteRoute._addFileChildren(
  CreditsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRoute,
  CreditsRouteRoute: CreditsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
